#!/bin/sh
# Usage: .ci_helpers/clone OWNER REPOSITORY [DIR] [BRANCH] [HEAD]
#
# Creates a shallow clone, checking out the specified branch.  If BRANCH is
# omitted or if there is no branch with that name, checks out origin/HEAD
# from the samtools/htslib repository.
#
# If ran from an existing git clone, we scan the first few commits from $HEAD
# to look for htslib#<PR> and use this PR number as the htslib branch to
# checkout.  This is useful when making joint PRs for samtools/htslib
# or bcftools/htslib

echo CLONE: ${@+"$@"}

owner=$1
repository="https://github.com/$owner/$2"
localdir=$3
branch=$4
head=$5

ref=''
[ -n "$branch" ] && ref=$(git ls-remote --heads "$repository" "$branch" 2>/dev/null)
[ -z "$ref" ] && repository='https://github.com/samtools/htslib.git'

set -x
git clone --recurse-submodules --shallow-submodules --depth=50 ${ref:+--branch="$branch"} "$repository" "$localdir"

# Automatically look for htslib#PR-number in recent commit messages
if [ -z "$ref" -a "x$head" != "x" ]
then
    htslib_PR=`git log -2 --format=%s $head | sed -n 's/.*htslib#\([0-9]*\).*/\1/p' | head -1`
    if [ "x$htslib_PR" != "x" ]
    then
        cd "$localdir"
        git fetch https://github.com/samtools/htslib.git "pull/$htslib_PR/head"
        git checkout FETCH_HEAD
    fi
fi
