name: Solaris
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  solaris-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    name: Solaris (x86-64)
    steps:
    # Outside VM
    - name: Install git
      run: |
        sudo apt-get install -y git

    - name: Checkout
      # This is actions/checkout@v6.0.2
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 1

    - name: Clone htslib
      run: |
        git config --global --add safe.directory `pwd`
        mkdir -p hidden-htslib
        htslib_pr=`git log -2 --format='%s' | sed -n 's/.*htslib#\([0-9]*\).*/\1/p'`
        .ci_helpers/clone ${GITHUB_REPOSITORY_OWNER} htslib hidden-htslib ${GITHUB_HEAD_REF:-$GITHUB_REF_NAME} $htslib_pr
          
    # Outside/Inside VM
    - name: Dependencies
      uses: vmactions/solaris-vm@v1
      with:
        release: "11.4-clang-19"
        # Note to use this you may need to merge all the steps into one.
        #debug-on-error: true
        #vnc-password: ${{ secrets.VNC_PASSWORD }}
        usesh: true
        cpu: 4
        prepare: |
          pkg install autoconf automake bash curl bzip2

    # Inside VM
    - name: Build htslib
      shell: solaris {0}
      run: |
        htsdir="`realpath .`/installed-htslib"

        # The C library does casting in CMSG_SPACE, breaking ref_cache.
        # It also doesn't like -fstack-protector, but we only check compile
        # rather than link time, so disable that too.  We add to CPPFLAGS
        # as it occurs after REF_CACHE_EXTRA_C_FLAGS.
        cd hidden-htslib
        autoreconf -i
        ./configure --prefix="$htsdir" --enable-werror CPPFLAGS="-Wno-sign-conversion -fno-stack-protector" --without-curses
        gmake -j 5 &&
        gmake install

    - name: Configure samtools
      shell: solaris {0}
      run: |
        htsdir="`realpath .`/installed-htslib"
        autoreconf -i
        with_htslib="--with-htslib=$htsdir"
        ldflags="-Wl,-rpath=${htsdir}/lib"
        # -Wno-char-subscripts turns off errors such as phase.c:460, which are
        # false alarms anyway.
        ./configure $with_htslib --enable-werror LDFLAGS="$ldflags" CFLAGS="-g -O3 -Wno-char-subscripts"

    - name: Build
      shell: solaris {0}
      run: |
          gmake -j5

    - name: Test
      shell: solaris {0}
      run: |
          # We need more compliant versions of tr and grep.
          PATH=/usr/xpg4/bin:$PATH
          export PATH
          htsdir="`realpath .`/installed-htslib"
          gmake check BGZIP=$htsdir/bin/bgzip
